# Generated by Django 4.0.3 on 2022-08-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeventApp', '0002_addevent_location_alter_addevent_fromdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=122)),
                ('lang', models.CharField(default='', max_length=122)),
            ],
        ),
        migrations.AddField(
            model_name='addevent',
            name='city',
            field=models.CharField(default='pune', max_length=122),
        ),
        migrations.AddField(
            model_name='addevent',
            name='eventermail',
            field=models.CharField(default='bankpay980@gmail.com', max_length=122),
        ),
    ]
